####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  product-crud-mysql-data:
    driver: local

  # Redis Data
  product-crud-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: product-crud-mysql
    volumes:
      - product-crud-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=product-crud
      - MYSQL_DATABASE=product-crud
      - MYSQL_USER=product-crud
      - MYSQL_PASSWORD=product-crud

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: product-crud-redis
    command: --appendonly yes
    volumes:
      - product-crud-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.0-caddy
    container_name: product-crud-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: product-crud-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache